### ISSUE TITLE
Terminal commands and output overwriting code cell contents

### ISSUE THREAD

**Issue by edrogersamfam** [ryantam626/jupyterlab_black#4] opened 2018-08-04 21:26 UTC
I'm using `jupyterlab_black v0.1.4`, and I'm seeing a strange behavior where code cells are overwritten by what should be executed in a terminal.

I've made a screencast video (as a large GIF) to demonstrate the problem here:
https://github.com/edrogersamfam/jupyterlab_black/blob/bug/terminal_in_codecell/jupyterlab_black_bug_demo.gif

Long story short, attempting to use the Black formatter on a code cell inevitably overwrites the cell with
```
from black import format_str

with open("/tmp/jupyterlab_black_working.py", "r") as file_:
    unformatted = file_.read()
formatted = format_str(unformatted, line_length=110)
with open("/tmp/jupyterlab_black_working.py", "w") as file_:
    file_.write(
        ""
        + formatted
    )
[1mreformatted -[0m
[1mAll done! ✨ 🍰 ✨[0m
[1m1 file reformatted[0m.[0m
```

### My set up:
| Software                     | Reported Version                                                                                                 |
|------------------------------|------------------------------------------------------------------------------------------------------------------|
| Linux                        | `Linux ip-172-32-1-52 4.15.0-1009-aws #9-Ubuntu SMP Wed May 16 15:22:54 UTC 2018 x86_64 x86_64 x86_64 GNU/Linux` |
| Ubuntu                       | `DISTRIB_DESCRIPTION="Ubuntu 18.04.1 LTS"`                                                                       |
| Python                       | `Python 3.6.5`                                                                                                   |
| pip                          | `pip 18.0 from /home/ubuntu/jupyterlab/lib/python3.6/site-packages/pip (python 3.6)`                             |
| jupyter                      | `4.4.0`                                                                                                          |
| black                        | `black, version 18.6b4`                                                                                          |
| JupyterLab                   | `JupyterLab v0.33.6`                                                                                             |
| @ryantam626/jupyterlab_black | `@ryantam626/jupyterlab_black v0.1.4`                                                                            |
| Other JupyterLab extensions: | `nbdime-jupyterlab v0.4.0`                                                                                       |

### My install process:
After creating and activating a virtualenv, I install extensions for both jupyter notebook and jupyter lab:
```
python3 -m pip install -U pip
python3 -m pip install --upgrade jupyter_contrib_nbextensions
python3 -m pip install --upgrade jupyter_nbextensions_configurator
python3 -m pip install -U autopep8 nbdime
python3 -m pip install -U jupyterlab black jupyterlab-git jupyterlab_latex

jupyter contrib nbextension install --sys-prefix
jupyter nbextensions_configurator enable --sys-prefix
jupyter nbextension enable toc2/main --user
jupyter nbextension enable code_prettify/autopep8 --user
nbdime extensions --enable --sys-prefix

jupyter labextension install --no-build @ryantam626/jupyterlab_black
jupyter lab build
```

### `pip freeze`:
```
appdirs==1.4.3
attrs==18.1.0
autopep8==1.3.5
backcall==0.1.0
black==18.6b4
bleach==2.1.3
certifi==2018.4.16
chardet==3.0.4
click==6.7
colorama==0.3.9
decorator==4.3.0
entrypoints==0.2.3
gitdb2==2.0.4
GitPython==2.1.11
html5lib==1.0.1
idna==2.7
ipykernel==4.8.2
ipython==6.5.0
ipython-genutils==0.2.0
jedi==0.12.1
Jinja2==2.10
jsonschema==2.6.0
jupyter-client==5.2.3
jupyter-contrib-core==0.3.3
jupyter-contrib-nbextensions==0.5.0
jupyter-core==4.4.0
jupyter-highlight-selected-word==0.2.0
jupyter-latex-envs==1.4.4
jupyter-nbextensions-configurator==0.4.0                                                                                                                                  jupyterlab==0.33.6
jupyterlab-git==0.1.2
jupyterlab-latex==0.3.1
jupyterlab-launcher==0.11.2
lxml==4.2.4
MarkupSafe==1.0
mistune==0.8.3
nbconvert==5.3.1
nbdime==1.0.2
nbformat==4.4.0
notebook==5.6.0
pandocfilters==1.4.2
parso==0.3.1
pexpect==4.6.0
pickleshare==0.7.4
prometheus-client==0.3.1
prompt-toolkit==1.0.15
psutil==5.4.6
ptyprocess==0.6.0
pycodestyle==2.4.0
Pygments==2.2.0
python-dateutil==2.7.3
PyYAML==3.13
pyzmq==17.1.0
requests==2.19.1
Send2Trash==1.5.0
simplegeneric==0.8.1
six==1.11.0
smmap2==2.0.4
terminado==0.8.1
testpath==0.3.1
toml==0.9.4
tornado==5.1
traitlets==4.3.2
urllib3==1.23
wcwidth==0.1.7
webencodings==0.5.1
```

I'm really excited to see this extension, and would love to help in any way I can. Thanks for making it.

**Comment by ryantam626** [comment] 2018-08-04 21:43
Oh wow! That's a really detailed bug report!

That's really weird, it seemed like the template strings on [this line](https://github.com/ryantam626/jupyterlab_black/blob/ab270b16609bd2bf27801a172cc78a11af6606c6/src/index.ts#L152) :thinking: While the code indent option is correctly templated..

~Could you confirm that you are just using vanilla pip without venv/pipenv/conda/something else?~ I now see you said you are using venv, sorry!

Also what's your node and npm version? And also what browser (and its version) are you using?

**Comment by edrogersamfam** [comment] 2018-08-05 12:20
Didn't mean to flood you with information. Very interested to diagnose this, though. 😄 

My npm version is 3.5.2
My node version is v8.10.0

**Comment by ryantam626** [comment] 2018-08-05 12:31
Hmm.. even though your npm and node is a bit outdated, it should still work.. (I used template strings which is >v4.0.0 for node as noted [here](https://nodejs.org/en/blog/release/v4.0.0/))

Can I see the full terminal output in JupyterLab? The plugin have overwritten the codecell content with the first thing that pops into the terminal due to the template strings not working as intended, I am thinking there might be extra clues in the full terminal output.

**Comment by edrogersamfam** [comment] 2018-08-05 17:57
I'll try out up-to-date versions of node & npm soon. In the meantime, I realize that I didn't share my browser version. It's Chrome for OSX Version 67.0.3396.99 (Official Build) (64-bit).

I also typically run with a zsh shell, which I thought might be causing the issue. Reverting to bash didn't resolve it though.

Here's the terminal output when running from bash in a virtualenv:
```
(jupyterlab) ubuntu@ip-172-32-1-40:~/jupyterlab$ jupyter lab --NotebookApp.token='' --no-browser --ip=${IP_ADDRESS}
[W 17:45:49.637 LabApp] All authentication is disabled.  Anyone who can connect to this server will be able to run code.
[I 17:45:49.663 LabApp] [jupyter_nbextensions_configurator] enabled 0.4.0
[I 17:45:49.665 LabApp] JupyterLab extension loaded from /home/ubuntu/jupyterlab/lib/python3.6/site-packages/jupyterlab
[I 17:45:49.665 LabApp] JupyterLab application directory is /home/ubuntu/jupyterlab/share/jupyter/lab
[W 17:45:49.730 LabApp] JupyterLab server extension not enabled, manually loading...
[I 17:45:49.731 LabApp] JupyterLab extension loaded from /home/ubuntu/jupyterlab/lib/python3.6/site-packages/jupyterlab
[I 17:45:49.731 LabApp] JupyterLab application directory is /home/ubuntu/jupyterlab/share/jupyter/lab
[I 17:45:49.736 LabApp] Serving notebooks from local directory: /home/ubuntu/jupyterlab
[I 17:45:49.736 LabApp] The Jupyter Notebook is running at:
[I 17:45:49.736 LabApp] http://172.32.1.40:8888/
[I 17:45:49.736 LabApp] Use Control-C to stop this server and shut down all kernels (twice to skip confirmation).
TermSocket.open: 1
[I 17:45:51.784 LabApp] New terminal with specified name: 1
TermSocket.open: Opened 1
[W 17:45:54.453 LabApp] 404 GET /api/kernels/e1223258-f19c-44b7-9501-581659993f55/channels?session_id=4db5fa83-134b-41ec-bf80-a72060768a04 (192.168.133.166): Kernel does not exist: e1223258-f19c-44b7-9501-581659993f55
[W 17:45:54.482 LabApp] 404 GET /api/kernels/e1223258-f19c-44b7-9501-581659993f55/channels?session_id=4db5fa83-134b-41ec-bf80-a72060768a04 (192.168.133.166) 39.68ms referer=None
[W 17:45:55.037 LabApp] 404 GET /api/kernels/5b6b9686-3d7f-4130-a8dd-23a61fec6156/channels?session_id=3bd60405-8ba1-41cc-a272-9c07c5752111 (192.168.133.166): Kernel does not exist: 5b6b9686-3d7f-4130-a8dd-23a61fec6156
[W 17:45:55.038 LabApp] 404 GET /api/kernels/5b6b9686-3d7f-4130-a8dd-23a61fec6156/channels?session_id=3bd60405-8ba1-41cc-a272-9c07c5752111 (192.168.133.166) 2.84ms referer=None
[W 17:45:57.537 LabApp] 404 GET /api/kernels/5824b776-615e-4696-b93a-8b94a9ea041d/channels?session_id=ac614cef-432b-4025-84da-b41be3d7dd3a (192.168.133.166): Kernel does not exist: 5824b776-615e-4696-b93a-8b94a9ea041d
[W 17:45:57.538 LabApp] 404 GET /api/kernels/5824b776-615e-4696-b93a-8b94a9ea041d/channels?session_id=ac614cef-432b-4025-84da-b41be3d7dd3a (192.168.133.166) 2.77ms referer=None
[W 17:45:57.740 LabApp] 404 GET /api/kernels/5824b776-615e-4696-b93a-8b94a9ea041d/channels?session_id=1e9fa173-7977-42c0-abdb-ba2b8118d92d (192.168.133.166): Kernel does not exist: 5824b776-615e-4696-b93a-8b94a9ea041d
[W 17:45:57.740 LabApp] 404 GET /api/kernels/5824b776-615e-4696-b93a-8b94a9ea041d/channels?session_id=1e9fa173-7977-42c0-abdb-ba2b8118d92d (192.168.133.166) 2.37ms referer=None
[I 17:46:09.671 LabApp] 302 GET / (192.168.133.166) 0.63ms
Websocket closed
[I 17:46:10.896 LabApp] New terminal with automatic name: 2
[I 17:46:11.718 LabApp] Kernel started: b5116113-5ecb-4cd2-a74c-c5f4d0ffe967
[I 17:46:11.837 LabApp] Kernel started: c6030e81-835b-4920-9914-88400224e14f
[I 17:46:11.842 LabApp] Build is up to date
TermSocket.open: 2
TermSocket.open: Opened 2
[I 17:46:14.378 LabApp] Adapting to protocol v5.1 for kernel c6030e81-835b-4920-9914-88400224e14f
[I 17:46:14.545 LabApp] Adapting to protocol v5.1 for kernel b5116113-5ecb-4cd2-a74c-c5f4d0ffe967
[I 17:46:14.896 LabApp] Adapting to protocol v5.1 for kernel c6030e81-835b-4920-9914-88400224e14f
[I 17:46:16.312 LabApp] Adapting to protocol v5.1 for kernel b5116113-5ecb-4cd2-a74c-c5f4d0ffe967
[I 17:48:12.354 LabApp] Saving file at /test/versions.ipynb
[I 17:48:39.856 LabApp] Saving file at /test/Test of Jupyter Lab Black Extension.ipynb
```
Nothing gets appended to this output when clicking the "Apply Black Formatter" command in JupyterLab.

Interestingly though, the output is slightly different when run with a bash terminal. The code cell was overwritten with:
```
/home/ubuntu/jupyterlab/bin/black - <<I97Qo3mjGJLySbuljz1Fzvh1ulPWBQdkG0QZ
from black import format_str
with open('/tmp/jupyterlab_black_working.py', 'r') as file_:
    unformatted = file_.read()
formatted = format_str(unformatted, line_length=110)
with open('/tmp/jupyterlab_black_working.py', 'w') as file_:
    file_.write("" + formatted)
I97Qo3mjGJLySbuljz1Fzvh1ulPWBQdkG0QZ
```

**Comment by ryantam626** [comment] 2018-08-05 18:25
Hmm interesting with the change with bash instead of zsh. (I use zsh myself as well, so probably not the issue)

I just realised there is a mistake with your config, you need to set the path to python, not path to black, i.e. it should be `/home/ubuntu/jupyterlab/bin/python`. But I have a feeling that that alone doesn't fix the issue.. 

Also, if you go to `Running` in JupyterLab, do you see a running terminal session?

**Comment by edrogersamfam** [comment] 2018-08-06 01:55
### An (unsuccessful) attempt with the previous set up, despite fixing the `blackPythonBin` value

The path to python vs path to black issue seemed to be a factor, but, as you suspected, not the whole issue. I swapped it out, and the first time after, when I ran the formatter, it swapped out single quotes for double, and otherwise left the code cell intact. Unfortunately, on the next code cell I applied the formatter, the command reverted to the previous, problematic behavior. 😕 

The code cell:
```
# re-run merge, 
df_merge2=pd.merge(df_merge1,df_ciinsn,how='inner',left_on=['polnum','dr_first_name', 'dr_mid', 'dr_last_name'],
                                                  right_on=['polnum','ins_first_name','ins_mid','ins_last_name'])
print("# records after merge on policy number and name: %d"%(len(df_merge2)))

# delete, duplicate after inner-join:
del df_merge2['ins_first_name']
del df_merge2['ins_mid']
del df_merge2['ins_last_name']
```
got converted to:
```
cat > /tmp/jupyterlab_black_working.py <<I97Qo3mjGJLySbuljz1Fzvh1ulPWBQdkG0QZ
> # re-run merge, 
> df_merge2=pd.merge(df_merge1,df_ciinsn,how='inner',left_on=['polnum','dr_first_name', 'dr_mid', 'dr_last_name'],
>                                                   right_on=['polnum','ins_first_name','ins_mid','ins_last_name'])
> print("# records after merge on policy number and name: %d"%(len(df_merge2)))
> 
> # delete, duplicate after inner-join:
> del df_merge2['ins_first_name']
> del df_merge2['ins_mid']
> del df_merge2['ins_last_name']
> I97Qo3mjGJLySbuljz1Fzvh1ulPWBQdkG0QZ
/home/ubuntu/jupyterlab/bin/python3 - <<I97Qo3mjGJLySbuljz1Fzvh1ulPWBQdkG0QZ
from black import format_str
with open('/tmp/jupyterlab_black_working.py', 'r') as file_:
    unformatted = file_.read()
formatted = format_str(unformatted, line_length=110)
with open('/tmp/jupyterlab_black_working.py', 'w') as file_:
    file_.write("" + formatted)
I97Qo3mjGJLySbuljz1Fzvh1ulPWBQdkG0QZ
```

Checking over in the "Running" tab on JupyterLab, there is a running terminal session. And its output includes some formatted code I would expect...
```
(jupyterlab) ubuntu@ip-172-32-1-40:~/jupyterlab$ cat /tmp/jupyterlab_black_working.py
Cl3PsCL5Ionv1d9tQMvNXRtz5aXUHj2VMk3mnn7Sg179c7d99e61-0713-458c-a47e-1f8343085aed# re-run merge,
df_merge2 = pd.merge(
    df_merge1,
    df_ciinsn,
    how="inner",
    left_on=["polnum", "dr_first_name", "dr_mid", "dr_last_name"],
    right_on=["polnum", "ins_first_name", "ins_mid", "ins_last_name"],
)
print("# records after merge on policy number and name: %d" % (len(df_merge2)))

# delete, duplicate after inner-join:
del df_merge2["ins_first_name"]
del df_merge2["ins_mid"]
del df_merge2["ins_last_name"]
(jupyterlab) ubuntu@ip-172-32-1-40:~/jupyterlab$
```

Hopefully there's some clues in there.

### Another (unsuccessful) attempt with updated Node and npm.

I updated Node and npm, so that my set up is now:

| Software                     | Reported Version                                                                                                   |
|------------------------------|--------------------------------------------------------------------------------------------------------------------|
| Linux                        | `Linux ip-172-32-1-183 4.15.0-1016-aws #16-Ubuntu SMP Wed Jul 18 09:20:54 UTC 2018 x86_64 x86_64 x86_64 GNU/Linux` |
| Ubuntu                       | `DISTRIB_DESCRIPTION="Ubuntu 18.04.1 LTS"                                                                          |
| Python                       | `Python 3.6.5`                                                                                                     |
| pip                          | `pip 18.0 from /home/ubuntu/jupyterlab/lib/python3.6/site-packages/pip (python 3.6)`                               |
| jupyter                      | `4.4.0`                                                                                                            |
| black                        | `black, version 18.6b4`                                                                                            |
| node                         | `v8.11.3`                                                                                                          |
| npm                          | `6.3.0`                                                                                                            |
| JupyterLab                   | `JupyterLab v0.33.6`                                                                                               |
| @ryantam626/jupyterlab_black | `@ryantam626/jupyterlab_black v0.1.4`                                                                              |
| Other JupyterLab extensions: | `nbdime-jupyterlab v0.4.0`                                                                                         |

I'm still seeing the issue, and the terminal session inside JupyterLab has similar content to before:
```
(jupyterlab) ubuntu@ip-172-32-1-183:~/jupyterlab$ cat /tmp/jupyterlab_black_worki
Cl3PsCL5Ionv1d9tQMvNXRtz5aXUHj2VMk3mnn7Sg179030b3d65-b0d1-444f-bb80-a93692fd849d# these cols have trailing whitespace, had some issues with bigquery rtrim()
for col in ["ins_predir", "ins_prev_zip", "ins_house_num", "ins_str_name", "ins_post_dir", "ins_str_type"]:
    df_ciinsn[col] = df_ciinsn[col].apply(str.strip)
rking.py <<I97Qo3mjGJLySbuljz1Fzvh1ulPWBQdkG0QZb$ cat > /tmp/jupyterlab_black_wor
/home/ubuntu/jupyterlab/bin/python3 - <<I97Qo3mjGJLySbuljz1Fzvh1ulPWBQdkG0QZ
from black import format_str
with open('/tmp/jupyterlab_black_working.py', 'r') as file_:
    unformatted = file_.read()
formatted = format_str(unformatted, line_length=110)
with open('/tmp/jupyterlab_black_working.py', 'w') as file_:
    file_.write("Cl3PsCL5Ionv1d9tQMvNXRtz5aXUHj2VMk3mnn7Sg179a452313d-e322-45d0-8057-00d618d1a0a5" + formatted)
I97Qo3mjGJLySbuljz1Fzvh1ulPWBQdkG0QZ
> # re-run merge,
_name', 'dr_mid', 'dr_last_name'],ciinsn,how='inner',left_on=['polnum','dr_first_
t_name','ins_mid','ins_last_name'])                 right_on=['polnum','ins_first
> print("# records after merge on policy number and name: %d"%(len(df_merge2)))
>
> # delete, duplicate after inner-join:
> del df_merge2['ins_first_name']
> del df_merge2['ins_mid']
> del df_merge2['ins_last_name']
> I97Qo3mjGJLySbuljz1Fzvh1ulPWBQdkG0QZ
cat /tmp/jupyterlab_black_working.py
thon3 - <<I97Qo3mjGJLySbuljz1Fzvh1ulPWBQdkG0QZab$ /home/ubuntu/jupyterlab/bin/pyt
> from black import format_str
> with open('/tmp/jupyterlab_black_working.py', 'r') as file_:
>     unformatted = file_.read()
> formatted = format_str(unformatted, line_length=110)
> with open('/tmp/jupyterlab_black_working.py', 'w') as file_:
0-8057-00d618d1a0a5" + formatted)9tQMvNXRtz5aXUHj2VMk3mnn7Sg179a452313d-e322-45d0
> I97Qo3mjGJLySbuljz1Fzvh1ulPWBQdkG0QZ
ing.pyerlab) ubuntu@ip-172-32-1-183:~/jupyterlab$ cat /tmp/jupyterlab_black_worki
Cl3PsCL5Ionv1d9tQMvNXRtz5aXUHj2VMk3mnn7Sg179a452313d-e322-45d0-8057-00d618d1a0a5# re-run merge,
df_merge2 = pd.merge(
    df_merge1,
    df_ciinsn,
    how="inner",
    left_on=["polnum", "dr_first_name", "dr_mid", "dr_last_name"],
    right_on=["polnum", "ins_first_name", "ins_mid", "ins_last_name"],
)
print("# records after merge on policy number and name: %d" % (len(df_merge2)))

# delete, duplicate after inner-join:
del df_merge2["ins_first_name"]
del df_merge2["ins_mid"]
del df_merge2["ins_last_name"]
(jupyterlab) ubuntu@ip-172-32-1-183:~/jupyterlab$
```

### A small note about versions...

In an overcompensation for previously having an out-of-date node & npm version, I first tried installing the latest node from source ( https://nodejs.org/dist/node-latest.tar.gz Node v10.8.0, which installs npm v6.3.0 ). Once that was installed, my "jupyter lab build" got stuck on "Resolving packages" for this extension. Not sure if that's due to some big change in upcoming versions of Node. Anyway, just an FYI.

**Comment by ryantam626** [comment] 2018-08-06 08:42
That's good! One step closer now!

Could you try `@ryantam626/jupyterlab_black@0.1.5-debug-issue-4.1`? A screenshot of the terminal + chrome console should be really helpful here! :crossed_fingers:

In that debug version, I added a bunch of logging and tried splitting the template string since I see that `${something}` works for you but not `${something}${somethingElse}` (actually on second thought this eliminates a race condition as well!)

**Comment by edrogersamfam** [comment] 2018-08-06 14:21
The good news: version 0.1.5-debug-issue-4.1 fixed the issue for me. 🎉 

The strange news: I see almost no logging messages when using it.

Running the formatter behaves as expected, even when run multiple times. The "Running" tab doesn't show a running terminal session, and the terminal window shows only:
```
unset HISTFILE
(jupyterlab) ubuntu@ip-172-32-1-183:~/jupyterlab$
```

Here's a screenshot:
![screenshot_jupyterlab_black-0.1.5-debug-issue-4.1.png](https://github.com/edrogersamfam/jupyterlab_black/raw/bug/terminal_in_codecell/screenshot_jupyterlab_black-0.1.5-debug-issue-4.1.png)

I also don't see any particular output at the terminal that launched the JupyterLab server, other than a couple of exceptions from tornado:
```
[I 13:47:13.070 LabApp] Writing notebook server cookie secret to /run/user/1000/jupyter/notebook_cookie_secret
[W 13:47:13.493 LabApp] All authentication is disabled.  Anyone who can connect to this server will be able to run code.
[I 13:47:13.536 LabApp] [jupyter_nbextensions_configurator] enabled 0.4.0
[I 13:47:13.540 LabApp] JupyterLab extension loaded from /home/ubuntu/jupyterlab/lib/python3.6/site-packages/jupyterlab
[I 13:47:13.540 LabApp] JupyterLab application directory is /home/ubuntu/jupyterlab/share/jupyter/lab
[W 13:47:13.661 LabApp] JupyterLab server extension not enabled, manually loading...
[I 13:47:13.661 LabApp] JupyterLab extension loaded from /home/ubuntu/jupyterlab/lib/python3.6/site-packages/jupyterlab
[I 13:47:13.661 LabApp] JupyterLab application directory is /home/ubuntu/jupyterlab/share/jupyter/lab
[I 13:47:13.665 LabApp] Serving notebooks from local directory: /home/ubuntu/jupyterlab
[I 13:47:13.665 LabApp] The Jupyter Notebook is running at:
[I 13:47:13.665 LabApp] http://172.32.1.183:8888/
[I 13:47:13.665 LabApp] Use Control-C to stop this server and shut down all kernels (twice to skip confirmation).
[I 13:47:55.194 LabApp] New terminal with automatic name: 1
TermSocket.open: 1
TermSocket.open: Opened 1
TermSocket.open: 1
TermSocket.open: Opened 1
[I 13:47:55.871 LabApp] Kernel started: a5eebabc-39e5-4af5-ad9c-e86f58158309
[I 13:47:55.879 LabApp] Kernel started: 6166f563-3982-46dd-b3e2-25c2110a9039
[I 13:47:56.156 LabApp] Build is up to date
[I 13:47:56.254 LabApp] Adapting to protocol v5.1 for kernel a5eebabc-39e5-4af5-ad9c-e86f58158309
[I 13:47:56.320 LabApp] Adapting to protocol v5.1 for kernel a5eebabc-39e5-4af5-ad9c-e86f58158309
[I 13:47:56.389 LabApp] Adapting to protocol v5.1 for kernel 6166f563-3982-46dd-b3e2-25c2110a9039
[I 13:47:56.455 LabApp] Adapting to protocol v5.1 for kernel 6166f563-3982-46dd-b3e2-25c2110a9039
Websocket closed
[I 13:49:06.619 LabApp] Starting buffering for a5eebabc-39e5-4af5-ad9c-e86f58158309:f9f5bc7d-79cd-437e-9354-8e049618e8d3
Exception in callback BaseAsyncIOLoop._handle_events(16, 1)
handle: <Handle BaseAsyncIOLoop._handle_events(16, 1)>
Traceback (most recent call last):
  File "/home/ubuntu/jupyterlab/lib/python3.6/site-packages/tornado/websocket.py", line 867, in write_message
    fut = self._write_frame(True, opcode, message, flags=flags)
  File "/home/ubuntu/jupyterlab/lib/python3.6/site-packages/tornado/websocket.py", line 846, in _write_frame
    return self.stream.write(frame)
  File "/home/ubuntu/jupyterlab/lib/python3.6/site-packages/tornado/iostream.py", line 570, in write
    self._check_closed()
  File "/home/ubuntu/jupyterlab/lib/python3.6/site-packages/tornado/iostream.py", line 1112, in _check_closed
    raise StreamClosedError(real_error=self.error)
tornado.iostream.StreamClosedError: Stream is closed

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/lib/python3.6/asyncio/events.py", line 145, in _run
    self._callback(*self._args)
  File "/home/ubuntu/jupyterlab/lib/python3.6/site-packages/tornado/platform/asyncio.py", line 122, in _handle_events
    handler_func(fileobj, events)
  File "/home/ubuntu/jupyterlab/lib/python3.6/site-packages/tornado/stack_context.py", line 300, in null_wrapper
    return fn(*args, **kwargs)
  File "/home/ubuntu/jupyterlab/lib/python3.6/site-packages/terminado/management.py", line 199, in pty_read
    client.on_pty_read(s)
  File "/home/ubuntu/jupyterlab/lib/python3.6/site-packages/terminado/websocket.py", line 64, in on_pty_read
    self.send_json_message(['stdout', text])
  File "/home/ubuntu/jupyterlab/lib/python3.6/site-packages/terminado/websocket.py", line 68, in send_json_message
    self.write_message(json_msg)
  File "/home/ubuntu/jupyterlab/lib/python3.6/site-packages/notebook/terminal/handlers.py", line 41, in write_message
    super(TermSocket, self).write_message(message, binary=binary)
  File "/home/ubuntu/jupyterlab/lib/python3.6/site-packages/tornado/websocket.py", line 262, in write_message
    return self.ws_connection.write_message(message, binary=binary)
  File "/home/ubuntu/jupyterlab/lib/python3.6/site-packages/tornado/websocket.py", line 869, in write_message
    raise WebSocketClosedError()
tornado.websocket.WebSocketClosedError
Websocket closed
[I 13:49:06.633 LabApp] Starting buffering for 6166f563-3982-46dd-b3e2-25c2110a9039:8f47ca76-1232-43e6-bb39-4f0b660da3a5
[I 13:49:07.347 LabApp] New terminal with automatic name: 2
TermSocket.open: 2
TermSocket.open: Opened 2
TermSocket.open: 1
TermSocket.open: Opened 1
[W 13:49:07.718 LabApp] Notebook test/versions.ipynb is not trusted
[W 13:49:07.722 LabApp] Notebook test/Test of Jupyter Lab Black Extension.ipynb is not trusted
[I 13:49:07.967 LabApp] Adapting to protocol v5.1 for kernel a5eebabc-39e5-4af5-ad9c-e86f58158309
[I 13:49:08.034 LabApp] Adapting to protocol v5.1 for kernel 6166f563-3982-46dd-b3e2-25c2110a9039
[I 13:49:08.305 LabApp] Build is up to date
[I 13:49:17.037 LabApp] Adapting to protocol v5.1 for kernel 6166f563-3982-46dd-b3e2-25c2110a9039
[I 13:49:30.997 LabApp] Starting buffering for a5eebabc-39e5-4af5-ad9c-e86f58158309:dc5895e9-b3a6-4776-abfe-277ff2bf55e1
[I 13:49:31.204 LabApp] Kernel restarted: a5eebabc-39e5-4af5-ad9c-e86f58158309
[I 13:49:31.595 LabApp] Adapting to protocol v5.1 for kernel a5eebabc-39e5-4af5-ad9c-e86f58158309
[I 13:49:31.596 LabApp] Restoring connection for a5eebabc-39e5-4af5-ad9c-e86f58158309:dc5895e9-b3a6-4776-abfe-277ff2bf55e1
[I 13:49:31.596 LabApp] Replaying 3 buffered messages
[I 13:51:07.877 LabApp] Saving file at /test/versions.ipynb
[I 13:51:07.928 LabApp] Saving file at /test/Test of Jupyter Lab Black Extension.ipynb
```

Thanks for looking into this for me! It seems like you've isolated the issue. I'm super-excited to get using this extension, and I'll be on the lookout for a new release when you have a chance.

In the meantime, if you'd like me to try out any more tests, just let me know.

**Comment by ryantam626** [comment] 2018-08-06 14:52
YAY! The race condition is indeed the underlying issue, don't know how I missed it before :disappointed: 

Have publish v0.1.5 with the fix, more details [here](https://github.com/ryantam626/jupyterlab_black/commit/2d3ceb2accc80683f310403622f7df092af065ad) if you are interested!

And thanks for all the testing you have done :grin: !

**Comment by ryantam626** [comment] 2018-08-07 19:40
Oh and I have also hit the stuck at resolving package issue just today. It's an issue with nodejs >10 and yarn compatibility issues, downgraded to v9 and it worked fine for me!

**Closed as completed** 2018-08-24 16:21 UTC
